# Generated by Django 6.0.5 on 2026-06-03 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_title', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('double_room', 'Двухместный номер'), ('lux_room', 'Люкс комната'), ('single_room', 'Одноместный номер'), ('standard_room', 'стандарт комната')], default='standard_room', max_length=25)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(max_length=1000)),
                ('image_main', models.ImageField(upload_to='room_images/')),
                ('image_bathroom', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('occupied', 'Занят'), ('maintenance', 'На обслуживании')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guests_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('guest_first_name', models.CharField(max_length=100)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cyber_zone_hotel.room')),
            ],
        ),
    ]
