# Generated by Django 6.0.5 on 2026-06-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_zone_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('double_room', 'Двухместный номер'), ('lux_room', 'Люкс комната'), ('single_room', 'Одноместный номер')], default='single_room', max_length=25),
        ),
    ]
